disable declaration of module to avoid error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type '(...modules: any[]) => any', but here has type '{ exports: any; require(id: string): any; id: string; filename: string; loaded: boolean; parent: ...'