revert to changes of furny/DefinitelyTyped: disable declaration of module to avoid error TS2403 (@see: https://github.com/furny/DefinitelyTyped/commit/a776a77b707a69e1c7921c6ee9e95f931beb08ca)